version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: library_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: library
      MYSQL_USER: library_user
      MYSQL_PASSWORD: Library123!
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - rtc_net

  php:
    build: .
    container_name: library_php
    restart: always
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - rtc_net

  nginx:
    image: nginx:latest
    container_name: library_nginx
    restart: always
    expose:
      - "80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - rtc_net

networks:
  rtc_net:
    external: true

volumes:
  db_data:
